repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: bash -c 'flake8 src/data_maki/ && isort -c --diff src/data_maki/ && black --check src/data_maki/'
        language: system
        types: [python]
