name: CI

on:
  push:
    branches:
      - main
    paths:
      - "apps/solver/**"
      - "bun.lockb"
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-solver:
    strategy:
      matrix:
        include:
          - target: bun-linux-x64
            outfile: solver-linux-x64
          - target: bun-windows-x64
            outfile: solver-windows-x64.exe
          - target: bun-darwin-x64
            outfile: solver-macos-x64
          - target: bun-darwin-arm64
            outfile: solver-macos-arm64

    name: Build solver (${{ matrix.target }})
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build
        working-directory: apps/solver
        run: bun run build

      - name: Build (standalone)
        working-directory: apps/solver
        run: bun build --minify --sourcemap --compile --bytecode --target=${{ matrix.target }} --outfile=dist/${{ matrix.outfile }} dist/**/*.js

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: solver-${{ matrix.target }}
          path: apps/solver/dist/${{ matrix.outfile }}

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Test (schemas)
        working-directory: packages/schemas
        run: bun test

      - name: Test (mock server)
        working-directory: apps/mock-server
        run: bun test
