[package]
name = "algorithm-v3-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
lto = "thin"
opt-level = 3

[dependencies]
js-sys = "0.3.72"
once_cell = "1.20.2"
serde = { version = "1.0", features = ["derive"] }
ts-bindgen-rt = "0.5.0"
wasm-bindgen = "0.2.95"
